{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
      ports:
        - port: {{ .Values.app.port }}
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.db.name }}
      ports:
        - port: {{ .Values.db.port }}
          protocol: TCP
    - to: []
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
