apiVersion: v2
name: myapp
description: A Helm chart for nginx + postgres application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: db
    version: 0.1.0
    repository: "file://charts/db"
  - name: app
    version: 0.1.0
    repository: "file://charts/app"
    condition: app.enabled
